"""
Driver module constants.
"""

# Driver Status

DRIVER_STATUS_AVAILABLE = "AVAILABLE"
DRIVER_STATUS_ASSIGNED = "ASSIGNED"
DRIVER_STATUS_ON_TRIP = "ON_TRIP"
DRIVER_STATUS_INACTIVE = "INACTIVE"
DRIVER_STATUS_SUSPENDED = "SUSPENDED"

DRIVER_STATUSES = [
    DRIVER_STATUS_AVAILABLE,
    DRIVER_STATUS_ASSIGNED,
    DRIVER_STATUS_ON_TRIP,
    DRIVER_STATUS_INACTIVE,
    DRIVER_STATUS_SUSPENDED,
]


# License Types

LICENSE_TYPE_LMV = "LMV"
LICENSE_TYPE_HMV = "HMV"
LICENSE_TYPE_TRANSPORT = "TRANSPORT"
LICENSE_TYPE_COMMERCIAL = "COMMERCIAL"
LICENSE_TYPE_MCWG = "MCWG"

LICENSE_TYPES = [
    LICENSE_TYPE_LMV,
    LICENSE_TYPE_HMV,
    LICENSE_TYPE_TRANSPORT,
    LICENSE_TYPE_COMMERCIAL,
    LICENSE_TYPE_MCWG,
]