"""
Vehicle module constants.
"""

# Vehicle Status
# VEHICLE_STATUS_ACTIVE = "ACTIVE"
# VEHICLE_STATUS_INACTIVE = "INACTIVE"
# VEHICLE_STATUS_MAINTENANCE = "MAINTENANCE"
# VEHICLE_STATUS_RETIRED = "RETIRED"


# VEHICLE_STATUSES = [
#     VEHICLE_STATUS_ACTIVE,
#     VEHICLE_STATUS_INACTIVE,
#     VEHICLE_STATUS_MAINTENANCE,
#     VEHICLE_STATUS_RETIRED
# ]
# Vehicle Status

VEHICLE_STATUS_ACTIVE = "ACTIVE"
VEHICLE_STATUS_INACTIVE = "INACTIVE"
VEHICLE_STATUS_ON_TRIP = "ON_TRIP"
VEHICLE_STATUS_MAINTENANCE = "MAINTENANCE"

VEHICLE_STATUSES = [
    VEHICLE_STATUS_ACTIVE,
    VEHICLE_STATUS_INACTIVE,
    VEHICLE_STATUS_ON_TRIP,
    VEHICLE_STATUS_MAINTENANCE,
]


# Vehicle Types
VEHICLE_TYPE_BUS = "BUS"
VEHICLE_TYPE_TRUCK = "TRUCK"
VEHICLE_TYPE_VAN = "VAN"
VEHICLE_TYPE_CAR = "CAR"
VEHICLE_TYPE_MINI_BUS = "MINI_BUS"


VEHICLE_TYPES = [
    VEHICLE_TYPE_BUS,
    VEHICLE_TYPE_TRUCK,
    VEHICLE_TYPE_VAN,
    VEHICLE_TYPE_CAR,
    VEHICLE_TYPE_MINI_BUS
]


# Fuel Types
FUEL_TYPE_DIESEL = "DIESEL"
FUEL_TYPE_PETROL = "PETROL"
FUEL_TYPE_CNG = "CNG"
FUEL_TYPE_ELECTRIC = "ELECTRIC"
FUEL_TYPE_HYBRID = "HYBRID"


FUEL_TYPES = [
    FUEL_TYPE_DIESEL,
    FUEL_TYPE_PETROL,
    FUEL_TYPE_CNG,
    FUEL_TYPE_ELECTRIC,
    FUEL_TYPE_HYBRID
]