"""
Maintenance module constants.

Contains:
- Maintenance statuses
- Maintenance types
- Priority levels
- Payment statuses
"""

# ==========================================================
# Maintenance Status
# ==========================================================

MAINTENANCE_STATUS_SCHEDULED = "SCHEDULED"
MAINTENANCE_STATUS_IN_PROGRESS = "IN_PROGRESS"
MAINTENANCE_STATUS_COMPLETED = "COMPLETED"
MAINTENANCE_STATUS_CANCELLED = "CANCELLED"
MAINTENANCE_STATUS_OVERDUE = "OVERDUE"


MAINTENANCE_STATUSES = [
    MAINTENANCE_STATUS_SCHEDULED,
    MAINTENANCE_STATUS_IN_PROGRESS,
    MAINTENANCE_STATUS_COMPLETED,
    MAINTENANCE_STATUS_CANCELLED,
    MAINTENANCE_STATUS_OVERDUE,
]


# ==========================================================
# Active Maintenance Statuses
# ==========================================================

ACTIVE_MAINTENANCE_STATUSES = [
    MAINTENANCE_STATUS_SCHEDULED,
    MAINTENANCE_STATUS_IN_PROGRESS,
    MAINTENANCE_STATUS_OVERDUE,
]


# ==========================================================
# Closed Maintenance Statuses
# ==========================================================

CLOSED_MAINTENANCE_STATUSES = [
    MAINTENANCE_STATUS_COMPLETED,
    MAINTENANCE_STATUS_CANCELLED,
]


# ==========================================================
# Maintenance Types
# ==========================================================

MAINTENANCE_TYPE_GENERAL_SERVICE = "GENERAL_SERVICE"
MAINTENANCE_TYPE_OIL_CHANGE = "OIL_CHANGE"
MAINTENANCE_TYPE_ENGINE_SERVICE = "ENGINE_SERVICE"
MAINTENANCE_TYPE_BRAKE_SERVICE = "BRAKE_SERVICE"
MAINTENANCE_TYPE_TYRE_REPLACEMENT = "TYRE_REPLACEMENT"
MAINTENANCE_TYPE_BATTERY_REPLACEMENT = "BATTERY_REPLACEMENT"
MAINTENANCE_TYPE_CLUTCH_SERVICE = "CLUTCH_SERVICE"
MAINTENANCE_TYPE_GEARBOX_SERVICE = "GEARBOX_SERVICE"
MAINTENANCE_TYPE_SUSPENSION_SERVICE = "SUSPENSION_SERVICE"
MAINTENANCE_TYPE_AC_SERVICE = "AC_SERVICE"
MAINTENANCE_TYPE_ELECTRICAL_REPAIR = "ELECTRICAL_REPAIR"
MAINTENANCE_TYPE_BODY_REPAIR = "BODY_REPAIR"
MAINTENANCE_TYPE_ACCIDENT_REPAIR = "ACCIDENT_REPAIR"
MAINTENANCE_TYPE_INSURANCE_RENEWAL = "INSURANCE_RENEWAL"
MAINTENANCE_TYPE_PUC_RENEWAL = "PUC_RENEWAL"
MAINTENANCE_TYPE_FITNESS_RENEWAL = "FITNESS_RENEWAL"
MAINTENANCE_TYPE_PERMIT_RENEWAL = "PERMIT_RENEWAL"
MAINTENANCE_TYPE_ROAD_TAX_RENEWAL = "ROAD_TAX_RENEWAL"
MAINTENANCE_TYPE_OTHER = "OTHER"


MAINTENANCE_TYPES = [
    MAINTENANCE_TYPE_GENERAL_SERVICE,
    MAINTENANCE_TYPE_OIL_CHANGE,
    MAINTENANCE_TYPE_ENGINE_SERVICE,
    MAINTENANCE_TYPE_BRAKE_SERVICE,
    MAINTENANCE_TYPE_TYRE_REPLACEMENT,
    MAINTENANCE_TYPE_BATTERY_REPLACEMENT,
    MAINTENANCE_TYPE_CLUTCH_SERVICE,
    MAINTENANCE_TYPE_GEARBOX_SERVICE,
    MAINTENANCE_TYPE_SUSPENSION_SERVICE,
    MAINTENANCE_TYPE_AC_SERVICE,
    MAINTENANCE_TYPE_ELECTRICAL_REPAIR,
    MAINTENANCE_TYPE_BODY_REPAIR,
    MAINTENANCE_TYPE_ACCIDENT_REPAIR,
    MAINTENANCE_TYPE_INSURANCE_RENEWAL,
    MAINTENANCE_TYPE_PUC_RENEWAL,
    MAINTENANCE_TYPE_FITNESS_RENEWAL,
    MAINTENANCE_TYPE_PERMIT_RENEWAL,
    MAINTENANCE_TYPE_ROAD_TAX_RENEWAL,
    MAINTENANCE_TYPE_OTHER,
]


# ==========================================================
# Priority Levels
# ==========================================================

PRIORITY_LOW = "LOW"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_HIGH = "HIGH"
PRIORITY_CRITICAL = "CRITICAL"


MAINTENANCE_PRIORITIES = [
    PRIORITY_LOW,
    PRIORITY_MEDIUM,
    PRIORITY_HIGH,
    PRIORITY_CRITICAL,
]


# ==========================================================
# Payment Status
# ==========================================================

PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_PARTIAL = "PARTIAL"
PAYMENT_STATUS_PAID = "PAID"


PAYMENT_STATUSES = [
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PARTIAL,
    PAYMENT_STATUS_PAID,
]